version: '3.8'

services:
  pdf-archiver:
    build: .
    container_name: overleaf-pdf-archiver
    volumes:
      - ./logs:/app/logs
      - ./archive:/srv/overleaf-archives
      - ${OVERLEAF_COMPILE_DIR}:/compiles:ro
    environment:
      - SCAN_INTERVAL_SECONDS=${SCAN_INTERVAL_SECONDS}
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: overleaf-pdf-nginx
    volumes:
      - ./archive:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped
